services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  background-worker:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/rails
    environment:
      - REDIS_URL=redis://redis:6379/0
      - RATE_API_URL=http://rate-api:8080
    depends_on:
      - redis

  rate-api:
    image: tripladev/rate-api
    ports:
      - "8080:8080"

  interview-dev:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
    environment:
      - REDIS_URL=redis://redis:6379/0
      - RATE_API_URL=http://rate-api:8080
    depends_on:
      - rate-api
      - background-worker
